-- Enriched investment locations with more cities and detailed data
-- This adds new cities with profile matching and comprehensive metrics

-- Add new cities to investment_locations table

-- BARCELONA - Lifestyle & Growth
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Barcelona', 'Spain', 'ES', false,
  'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
  'Mediterranean hub with strong tourism demand and lifestyle appeal',
  4200, 8500, 4600, 9200, 3700, 7500,
  4.2, 5.8, 38,
  '[3.5, 7.8, 12.5, 16.2, 20.5]'::jsonb,
  '["Income Seeker", "Lifestyle Investor", "Growth Hunter"]'::jsonb,
  'Mature',
  9, 7, 7, 5,
  true,
  'Golden Visa available',
  7, 7,
  'Moderate - Tourist tax, rental restrictions in some areas',
  'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200',
  '["Strong tourism economy", "Mediterranean lifestyle", "Golden Visa pathway", "High rental demand", "Cultural and culinary hub"]'::jsonb
) ON CONFLICT DO NOTHING;

-- ATHENS - Growth Hunter paradise
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Athens', 'Greece', 'GR', false,
  'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800',
  'Emerging market with exceptional growth potential and affordability',
  2800, 5200, 3000, 5700, 2500, 4600,
  5.5, 7.2, 45,
  '[15.2, 22.8, 28.5, 35.2, 42.8]'::jsonb,
  '["Growth Hunter", "Income Seeker"]'::jsonb,
  'Emerging',
  7, 9, 6, 6,
  true,
  'Golden Visa (€250k minimum)',
  6, 6,
  'Moderate - Greek bureaucracy, language barrier, improving infrastructure',
  'https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200',
  '["Exceptional value for money", "Tourism boom post-recovery", "Golden Visa at €250k", "Strong short-term rental market", "Historic and cultural appeal"]'::jsonb
) ON CONFLICT DO NOTHING;

-- MIAMI - Sophisticated Builder & Lifestyle
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Miami', 'United States', 'US', false,
  'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=800',
  'International gateway with strong appreciation and lifestyle appeal',
  5800, 11500, 6300, 12500, 5100, 10200,
  4.5, 6.2, 32,
  '[8.5, 14.2, 22.8, 28.5, 35.2]'::jsonb,
  '["Sophisticated Builder", "Lifestyle Investor", "Growth Hunter"]'::jsonb,
  'Mature',
  9, 8, 7, 7,
  false,
  'No state income tax in Florida',
  8, 8,
  'High - Foreign investment restrictions, financing challenges, EB-5 visa expensive',
  'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=1200',
  '["No state income tax", "International business hub", "Strong Latin American ties", "Luxury condo market", "Year-round sunshine"]'::jsonb
) ON CONFLICT DO NOTHING;

-- BERLIN - Growth & Sophisticated
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Berlin', 'Germany', 'DE', false,
  'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800',
  'Emerging tech hub with strong fundamentals and growth trajectory',
  4500, 7800, 4900, 8500, 4000, 6900,
  3.8, 5.2, 28,
  '[12.5, 18.2, 25.5, 32.8, 38.5]'::jsonb,
  '["Growth Hunter", "Sophisticated Builder"]'::jsonb,
  'Emerging-Mature',
  8, 8, 7, 6,
  false,
  'None significant - EU member benefits',
  9, 7,
  'Moderate - Tenant-friendly regulations, German language for contracts',
  'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=1200',
  '["Startup and tech hub", "Strong rental demand", "EU largest economy", "Relatively affordable for capital city", "Cultural capital"]'::jsonb
) ON CONFLICT DO NOTHING;

-- BUDAPEST - Income Seeker & Growth
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Budapest', 'Hungary', 'HU', false,
  'https://images.unsplash.com/photo-1541114782935-0f9be1c3f0f4?w=800',
  'Value play with high yields and strong tourism fundamentals',
  2200, 4200, 2400, 4600, 1900, 3700,
  6.2, 8.5, 35,
  '[18.5, 25.2, 32.8, 38.5, 45.2]'::jsonb,
  '["Income Seeker", "Growth Hunter"]'::jsonb,
  'Emerging',
  7, 8, 7, 5,
  true,
  'Golden Visa (€250k bonds), low property taxes',
  6, 6,
  'Moderate - Language barrier, EU member, improving market transparency',
  'https://images.unsplash.com/photo-1541114782935-0f9be1c3f0f4?w=1200',
  '["Exceptional rental yields", "Low entry costs", "Golden Visa available", "Tourism hotspot", "EU membership"]'::jsonb
) ON CONFLICT DO NOTHING;

-- ALGARVE - Lifestyle & Income
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Algarve', 'Portugal', 'PT', true,
  'https://images.unsplash.com/photo-1551346320-c0253f170fcd?w=800',
  'Premier resort destination with strong rental yields and lifestyle appeal',
  3500, 6500, 3800, 7100, 3100, 5800,
  5.5, 7.2, 42,
  '[10.2, 15.8, 22.5, 28.2, 32.8]'::jsonb,
  '["Lifestyle Investor", "Income Seeker"]'::jsonb,
  'Mature',
  10, 6, 8, 4,
  true,
  'Golden Visa, NHR Tax Regime (if still available)',
  8, 7,
  'Low - English widely spoken, established expat community',
  'https://images.unsplash.com/photo-1551346320-c0253f170fcd?w=1200',
  '["World-class beaches", "Golf and resort lifestyle", "Strong vacation rental market", "300+ days of sunshine", "Golden Visa pathway"]'::jsonb
) ON CONFLICT DO NOTHING;

-- TALLINN - Growth Hunter
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Tallinn', 'Estonia', 'EE', false,
  'https://images.unsplash.com/photo-1553342385-111fd6bc6ab3?w=800',
  'Digital-first nation with tech ecosystem and emerging real estate market',
  2800, 4800, 3000, 5200, 2500, 4200,
  5.2, 6.8, 38,
  '[22.5, 28.8, 35.2, 42.5, 48.8]'::jsonb,
  '["Growth Hunter", "Sophisticated Builder"]'::jsonb,
  'Emerging',
  6, 9, 6, 7,
  false,
  'E-Residency program, EU member',
  7, 5,
  'Moderate - Small market, language barrier, digital-friendly regulations',
  'https://images.unsplash.com/photo-1553342385-111fd6bc6ab3?w=1200',
  '["Tech and startup hub", "E-Residency program", "Low property prices", "EU membership", "Digital infrastructure"]'::jsonb
) ON CONFLICT DO NOTHING;
