-- Additional UK Investment Locations
-- Comprehensive data for UK cities outside London and Manchester

-- BIRMINGHAM - Second City, Strong Growth
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Birmingham', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
  'UK''s second largest city with strong regeneration and high rental yields',
  3500, 5800, 3800, 6300, 3000, 5000,
  5.2, 6.8, 28,
  '[3.2, 5.8, 9.5, 12.8, 15.2]'::jsonb,
  '["Income Seeker", "Growth Hunter"]'::jsonb,
  'Emerging-Mature',
  6, 7, 8, 4,
  false,
  'None significant',
  9, 8,
  'Low - English speaking, established market, strong demand',
  'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200',
  '["Second largest UK city", "HS2 rail connectivity", "Strong rental demand", "Lower entry costs than London", "Major regeneration projects"]'::jsonb
) ON CONFLICT DO NOTHING;

-- EDINBURGH - Scottish Capital, Lifestyle Appeal
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Edinburgh', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
  'Historic Scottish capital with world-class culture and strong tourism fundamentals',
  4200, 7500, 4600, 8200, 3600, 6500,
  4.5, 6.2, 32,
  '[5.2, 8.5, 12.8, 16.5, 19.8]'::jsonb,
  '["Lifestyle Investor", "Income Seeker", "Sophisticated Builder"]'::jsonb,
  'Mature',
  9, 6, 8, 5,
  false,
  'None significant',
  9, 7,
  'Moderate - Festival season affects rentals, strong student demand',
  'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200',
  '["UNESCO World Heritage city", "Edinburgh Festival hub", "Strong tourism market", "Financial services center", "High quality of life"]'::jsonb
) ON CONFLICT DO NOTHING;

-- LEEDS - Northern Powerhouse, Tech Hub
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Leeds', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  'Fastest growing UK tech hub outside London with strong employment growth',
  3200, 5500, 3500, 6000, 2800, 4800,
  5.5, 7.2, 25,
  '[4.2, 7.8, 11.5, 15.2, 18.5]'::jsonb,
  '["Income Seeker", "Growth Hunter"]'::jsonb,
  'Emerging-Mature',
  7, 8, 8, 4,
  false,
  'None significant',
  9, 8,
  'Low - Strong infrastructure, young professional demand',
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
  '["Fastest growing tech hub", "Major legal and financial center", "Excellent transport links", "High rental yields", "Young professional population"]'::jsonb
) ON CONFLICT DO NOTHING;

-- BRISTOL - Creative Hub, Quality of Life
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Bristol', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  'Creative and cultural hub with exceptional quality of life and growth trajectory',
  4500, 7800, 4900, 8500, 3900, 6800,
  4.2, 5.8, 30,
  '[8.5, 12.8, 18.5, 22.8, 26.5]'::jsonb,
  '["Lifestyle Investor", "Growth Hunter", "Sophisticated Builder"]'::jsonb,
  'Mature',
  9, 7, 7, 5,
  false,
  'None significant',
  9, 7,
  'Moderate - High demand area, competitive market',
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
  '["Voted best UK city for quality of life", "Creative industries hub", "Strong tech sector", "Green and sustainable", "Close to London"]'::jsonb
) ON CONFLICT DO NOTHING;

-- LIVERPOOL - Heritage City, Regeneration
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Liverpool', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  'UNESCO Maritime Mercantile City with strong regeneration and tourism appeal',
  2800, 4800, 3000, 5200, 2400, 4200,
  6.2, 8.0, 28,
  '[5.8, 9.5, 14.2, 18.5, 22.8]'::jsonb,
  '["Income Seeker", "Growth Hunter"]'::jsonb,
  'Emerging',
  7, 8, 7, 4,
  false,
  'None significant',
  8, 7,
  'Low - Affordable entry, strong student market',
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
  '["UNESCO World Heritage site", "Beatles heritage tourism", "Major regeneration projects", "High rental yields", "Affordable entry point"]'::jsonb
) ON CONFLICT DO NOTHING;

-- NEWCASTLE - Emerging Market, Student Hub
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Newcastle', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  'Vibrant northern city with strong student population and emerging tech sector',
  2500, 4200, 2700, 4600, 2200, 3700,
  6.5, 8.2, 25,
  '[2.8, 5.5, 9.2, 12.5, 15.8]'::jsonb,
  '["Income Seeker", "Growth Hunter"]'::jsonb,
  'Emerging',
  7, 7, 8, 4,
  false,
  'None significant',
  8, 7,
  'Low - Strong student demand, affordable market',
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
  '["Major university city", "Strong nightlife and culture", "Low entry costs", "High rental yields from students", "Emerging tech sector"]'::jsonb
) ON CONFLICT DO NOTHING;

-- NOTTINGHAM - Student City, High Yields
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Nottingham', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  'Historic city with two major universities delivering consistent rental demand',
  2800, 4500, 3000, 4900, 2400, 3900,
  6.8, 8.5, 22,
  '[3.5, 6.2, 9.8, 12.5, 15.2]'::jsonb,
  '["Income Seeker"]'::jsonb,
  'Mature',
  6, 6, 9, 3,
  false,
  'None significant',
  9, 8,
  'Low - Established student market, reliable yields',
  'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
  '["Two major universities (60,000+ students)", "Highest rental yields in UK", "Central England location", "Reliable student demand", "Affordable entry costs"]'::jsonb
) ON CONFLICT DO NOTHING;

-- GLASGOW - Scottish Second City
INSERT INTO investment_locations (
  city, country, country_code, is_preferred, image_url, description,
  price_per_sqm_eur_min, price_per_sqm_eur_max,
  price_per_sqm_usd_min, price_per_sqm_usd_max,
  price_per_sqm_gbp_min, price_per_sqm_gbp_max,
  rental_yield_min, rental_yield_max,
  days_to_rent_avg,
  price_growth_5y,
  investor_profile_match,
  market_maturity,
  lifestyle_appeal,
  growth_potential,
  income_stability,
  sophistication_required,
  residency_program,
  tax_advantages,
  market_transparency,
  liquidity_score,
  entry_barriers,
  hero_image_url,
  highlights
) VALUES (
  'Glasgow', 'United Kingdom', 'UK', false,
  'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
  'Scotland''s largest city with vibrant culture and strong regeneration',
  2800, 5200, 3000, 5700, 2400, 4500,
  5.8, 7.5, 28,
  '[4.2, 7.5, 11.8, 15.2, 18.5]'::jsonb,
  '["Income Seeker", "Growth Hunter"]'::jsonb,
  'Emerging-Mature',
  7, 7, 8, 4,
  false,
  'None significant',
  8, 7,
  'Low - Affordable, strong rental market',
  'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200',
  '["Scotland''s largest city", "Major cultural center", "Strong university presence", "Regeneration projects", "Affordable entry point"]'::jsonb
) ON CONFLICT DO NOTHING;

-- Create or update comment on UK market characteristics
COMMENT ON TABLE investment_locations IS 'Investment locations with profile matching. UK cities offer strong legal frameworks, transparent markets, and consistent rental demand. No residency programs but stable political environment and established property rights.';
